import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from 'react-icons/ai';
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Eric Fiorani Portfolio</title>
        <meta name="description" content="Generated by Eric"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section>

          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Developed by Eric</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="cursor-pointer text-2xl"/></li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded ml-8" href="#">Resume</a></li>
            </ul>
          </nav>

          <div className="text-center p-10">
            
            <h2 className="text-5xl md:text-6xl py-2 text-teal-600 font-medium">Eric Fiorani</h2>
            <h3 className="text-2xl md:text-3xl py-2">Developer & Designer</h3>
            <p className="text-md md:text-xl py-5 leading-8 text-gray-800 max-width-xl mx-auto">A passion for Design and Front-End Development creating visually appealing web apps and ensuring a seamless and engaging user experience.</p>
            
            <div className="flex text-3xl md:text-6xl justify-center gap-2 py-3 text-gray-600">
              <AiFillTwitterCircle/>
              <AiFillLinkedin/>
              <AiFillGithub/>
            </div>

            <div className="relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 mx-auto overflow-hidden">
              <Image src={deved} layout="fill" objectFit="cover"/>
            </div>
              
          </div>

        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a freelance and employeed developer, I&rsquo;ve done remote work for small, medium and large <span className="text-teal-500">agencies</span>. Created scalable designs and product launches leading to <span className="text-teal-500">multi-seven figure revenue</span> campaigns.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer a wide range of services, including landing page design, web applications, digital marketing, conversion rate optimization and more&hellip;
            </p>
          </div>
        </section>

        <section>
          <div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <Image src={design} width={100} height={100}/>
                <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
                <p className="py-2">Creating elegant designs suited for your needs following core design theory.</p>
                <h4 className="py-4 text-teal-600">Design tools I Use</h4>
                <p className="text-gray-300 py-1">Photoshop</p>
                <p className="text-gray-300 py-1">Figma</p>
              </div>

              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <Image src={code} width={100} height={100}/>
                <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
                <p className="py-2">Creating elegant designs suited for your needs following core design theory.</p>
                <h4 className="py-4 text-teal-600">Design tools I Use</h4>
                <p className="text-gray-300 py-1">Photoshop</p>
                <p className="text-gray-300 py-1">Figma</p>
              </div>

              <div className="text-center shadow-lg p-10 rounded-xl my-10">
                <Image src={consulting} width={100} height={100}/>
                <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
                <p className="py-2">Creating elegant designs suited for your needs following core design theory.</p>
                <h4 className="py-4 text-teal-600">Design tools I Use</h4>
                <p className="text-gray-300 py-1">Photoshop</p>
                <p className="text-gray-300 py-1">Figma</p>
              </div>
            </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p>needs text paragraph</p>
          </div>
          <div>
            <div>
              <Image src={web1}/>
            </div>
            <div>
              <Image src={web2}/>
            </div>
            <div>
              <Image src={web3}/>
            </div>
            <div>
              <Image src={web4}/>
            </div>
            <div>
              <Image src={web5}/>
            </div>
            <div>
              <Image src={web6}/>
            </div>
          </div>
        </section>

      </main>
    </div>
  );
}
